services:
  jupyterlab:
    build: .
    image: jupyterlab-test-img
    container_name: jupyterlab-test
    volumes:
      - ./work:/work
    ports:
      - "8888:8888"
    command: jupyter-lab --ip 0.0.0.0 --allow-root --NotebookApp.token='' -b localhost
